version: "3.9"
services:
  postgres:
    container_name: medusa-postgres
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: medusa-redis
    restart: always
    image: redis
    ports:
      - 6389:6379

volumes:
  postgres:
